### ISSUE TITLE
Desenvolver pipeline de construção do projeto

### ISSUE THREAD

**Issue by joepreludian** [CodeForCuritiba/onibus-io-backend#2]
Itens para se trabalhar.

* Fazer linting do código;
* Teste;
* Deploy

* Construir um arquivo do docker compose para possibilitar o desenvolvimento da aplicação;
* Criar um projeto com mongo já atachado e com variáveis pré-configuradas.

**Comment by joepreludian** [comment]
Caro @luizvnasc... Dúvida... Como está feita a string para compilação do projeto? Pelo que eu vi voce está usando variáveis de ambiente. Confere?

**Comment by joepreludian** [comment]
Partindo da premissa que eu estou com já com o golang configurado e pronto para operação, como faria para rodar o projeto? Thanks.

**Comment by luizvnasc** [comment]
> Caro @luizvnasc... Dúvida... Como está feita a string para compilação do projeto? Pelo que eu vi voce está usando variáveis de ambiente. Confere?

Sim, eu não gostaria de colocar essas variáveis aqui então vou te passar via telegram blz?

> Partindo da premissa que eu estou com já com o golang configurado e pronto para operação, como faria para rodar o projeto? Thanks.

 Execute `go build` e depois do build execute `./onibus-io-backend`

**Comment by joepreludian** [comment]
@luizvnasc eu vou aguardar então pelo TGRAM, até pq eu preciso de instruções claras para rodar em desenvolvimento, partindo da premissa que outras pessoas vão poder colaborar com o projeto tbm, e quais são os parâmetros pra produção.

Irei te contactar por lá.

**Comment by joepreludian** [comment]
Tente me mandar as credenciais até o final da tarde pq hoje à noite eu vou trabalhar no projeto, normalizando ele. Muito bacaninha o GO para construção de APIs. =D

**Comment by luizvnasc** [comment]
@joepreludian Vou fazer melhor, vou alterar o config que eu peguei do cwbus-hist e vou limpar as variáveis desnecessárias. Também vou testar se com a URL readonly da [base de dados](https://github.com/CodeForCuritiba/onibus-io/blob/master/base%20de%20dados/README.md) vai funcionar corretamente. Assim não temos que esconder nenhuma informação.

**Comment by joepreludian** [comment]
Pra continuarmos o trabalho eu ainda voto em fazermos assim: vc me passa só a parte relativa à configuração do BD (relativo a um mongo na maquina local). A API do onibus é pública ou precisa de credencial? A ideia é automatizar justamente seu codebase... e depois propomos esse enxugamento. o que acha?

Mas é bom saber o que é restrito, por exemplo, pra evitar DDoS ou qualquer outro tipo de ameaça.

**Comment by joepreludian** [comment]
Passando para dar um reporte sobre o projeto: Estou desenvolvendo em outra branch a pipeline que vai cuidar de fazer as seguintes atividades:

* Criar uma versão do projeto para desenvolvimento em GO usando docker (OK)
* Iniciar uma conexao mongodb exclusiva para o projeto (OK)
* Criar um container de importação dos dados que rodará um comando responsável por:
  * Fazer o download do arquivo direto do github release (OK)
  * Descompactar o arquivo ZIP;
  * Importar os dados JSON para o servidor mongodb recém criado;
  * Criar uma flag para que o programa importador não realize mais importações `data_imported.lock`;

Amanhã, assim que sobrar um tempo, eu implemento as rotinas de CI/CD  a ssim como documento como se trabalhar no projeto.

**Comment by joepreludian** [comment]
Senhores... O projeto já está sendo construído com o docker-compose e sendo feito push da imagem com o executável para o dockerhub. 

O `docker-compose up` já faz o papel de rodar o mongo, compilar e importar os arquivos.
Se voce remover o arquivo de lock `data_imported.lock` ele fará a importação novamente assim que voce executar o `docker-compose up`.
